SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


TRUNCATE TABLE `symptoms`;
INSERT INTO `symptoms` VALUES(2, 'ב. התנהגות');
INSERT INTO `symptoms` VALUES(3, 'קשב');
INSERT INTO `symptoms` VALUES(4, 'חרדה');
INSERT INTO `symptoms` VALUES(5, 'דיכאון');
INSERT INTO `symptoms` VALUES(6, 'ערך עצמי');
INSERT INTO `symptoms` VALUES(7, 'מיומנויות חברתיות');
INSERT INTO `symptoms` VALUES(8, 'טיפול זוגי');
INSERT INTO `symptoms` VALUES(9, 'אכילה');
INSERT INTO `symptoms` VALUES(10, 'ה.אישיות');
INSERT INTO `symptoms` VALUES(11, 'טראומה');
INSERT INTO `symptoms` VALUES(12, 'הדרכת הורים');
INSERT INTO `symptoms` VALUES(13, 'מ.לחץ');
INSERT INTO `symptoms` VALUES(14, 'PDD');
INSERT INTO `symptoms` VALUES(15, 'עבודה');
SET FOREIGN_KEY_CHECKS=1;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
